insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (1, 'Bashirian, Watsica and Sporer', 128);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (2, 'Rowe, Larkin and Conn', 64);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (3, 'Treutel, Keeling and Prosacco', 315);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (4, 'Feil Group', 174);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (5, 'Frami, Padberg and Schuppe', 206);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (6, 'Wintheiser LLC', 574);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (7, 'Simonis, Romaguera and Harvey', 92);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (8, 'Jacobson, Bosco and Kub', 34);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (9, 'Feeney Inc', 293);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (10, 'Schuppe, Glover and Heidenreich', 480);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (11, 'Daniel Group', 49);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (12, 'Flatley-Skiles', 588);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (13, 'Kunze-Hahn', 63);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (14, 'Schulist Inc', 191);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (15, 'Olson Inc', 60);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (16, 'Pouros Inc', 498);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (17, 'Wisoky, Gerhold and Skiles', 261);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (18, 'Wolf, Hilll and Turner', 113);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (19, 'Gutkowski-West', 63);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (20, 'Beer-Little', 584);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (21, 'Bashirian LLC', 133);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (22, 'Dicki, Barton and Torphy', 498);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (23, 'Brakus, Emmerich and McLaughlin', 440);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (24, 'Stokes and Sons', 185);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (25, 'Roob-Miller', 268);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (26, 'Mann, Murphy and Yost', 503);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (27, 'Kuhic Group', 4);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (28, 'Sawayn, Hand and Bailey', 65);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (29, 'Wolf, Abbott and Barton', 550);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (30, 'Dooley and Sons', 247);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (31, 'Littel, Schinner and Armstrong', 374);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (32, 'Buckridge Inc', 425);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (33, 'Dickinson LLC', 411);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (34, 'Wilderman, Watsica and Brown', 68);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (35, 'Cummings Group', 47);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (36, 'D''Amore Inc', 62);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (37, 'Bode-Nienow', 553);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (38, 'Price and Sons', 191);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (39, 'Bruen, Huel and Welch', 291);
insert into optimized_supply_chain.inventory (inventory_id, inventory_name, location_id) values (40, 'Conroy and Sons',64);
